version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      #command: gunicorn --bind 0.0.0.0:5000 manage:app
      #volumes:
      #- static_volume:/home/app/web/project/static
    expose:
      - 8000
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
      #volumes:
      #- static_volume:/home/app/web/project/static
    ports:
      - 80:80
    depends_on:
      - web
